p1: p1/Cargo.toml p1/src/*
	cd p1 && cargo run --release -- ../input.txt
.PHONY: p1

p1_test: p1/Cargo.toml p1/src/*
	cd p1 && cargo run -- example.txt
.PHONY: p1_test

p2: p2/Cargo.toml p2/src/*
	cd p2 && cargo run --release -- ../input.txt
.PHONY: p2

p2_test: p2/Cargo.toml p2/src/*
	cd p2 && cargo run -- example.txt
.PHONY: p2_test
