p1: p1/*
	cd p1 && ./main.py ../input.txt
.PHONY: p1

p1_test: p1/*
	cd p1 && ./main.py example.txt
.PHONY: p1_test

p2: p2/*
	cd p2 && ./main.py ../input.txt
.PHONY: p2

p2_test: p2/*
	cd p2 && ./main.py example.txt
.PHONY: p2_test
